---
title: "セ・リーグ 個人投手成績（規定投球回以上） 2023-05-17"
author: "hokmts"
date: "2023-05-17"
output:
  md_document:
#
df_print:
#
---
---
title: "セ・リーグ 個人投手成績（規定投球回以上）2023-05-17 "
pubDate: "May 17 2023"
description: "2023年5月16日時点の個人投手成績（規定投球回以上）の比較"
author: "hokmts"
tags: pitching, central-league
---

```{r setup, include=FALSE}
library(flexdashboard)
library("rvest")
library("dplyr")
library("tidyverse")
library("openxlsx")
library("ggplot2")
library("patchwork")
library("knitr")
library("kableExtra")
library("tidyverse")
library("cowplot")
library("gridExtra")
library("gganimate")
#library("transformr")
library("gifski")
library("gt")
library("DT")
library("readxl")
# font set
quartzFonts(Hirakaku=quartzFont(rep("HiraginoSans-W3",4)))
par(family="Hirakaku")
theme_set(theme_bw(base_family = "Hirakaku"))
# data load & pacific central data merge
pitch_stats <- read_xlsx("~/Public/baseball/2023/02data/02league/pit_c_2023cl.xlsx",
                       sheet = 'Sheet1')
#投手名スペース削除＆Key作成
pitch_stats$投手 <- str_replace(pitch_stats$投手 , pattern= "　", replacement="") 
pitch_stats <- mutate(pitch_stats,"投手名" =　pitch_stats$投手 )
#
pitch_data <- read_xlsx("~/Public/baseball/2023/02data/01game/pitchdata23.xlsx",
                  sheet = 'Sheet1')
#
pitch_data$X <- as.numeric(pitch_data$X)
pitch_data$Y <- as.numeric(pitch_data$Y)
pitch_data$球速 <- as.numeric(pitch_data$球速)
pitch_data$投球数1 <- as.numeric(pitch_data$投球数1)
# 空三振 見三振 replace 空振り 見逃し
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "空三振", "空振り", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "空三振", "空振り", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "空三振", "空振り", pitch_data$結果4 ) 
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "見三振", "見逃し", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "見三振", "見逃し", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "見三振", "見逃し", pitch_data$結果4 ) 
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "バ三振", "見逃し", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "バ三振", "見逃し", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "バ三振", "見逃し", pitch_data$結果4 ) 
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "四球", "ボール", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "四球", "ボール", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "四球", "ボール", pitch_data$結果4 ) 
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "死球", "ボール", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "死球", "ボール", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "死球", "ボール", pitch_data$結果4 ) 
pitch_data$結果2 <- ifelse(pitch_data$結果2 == "野選出", "失出塁", pitch_data$結果2 ) 
pitch_data$結果3 <- ifelse(pitch_data$結果3 == "野選出", "失出塁", pitch_data$結果3 ) 
pitch_data$結果4 <- ifelse(pitch_data$結果4 == "野選出", "失出塁", pitch_data$結果4 ) 
```


```{r , include=FALSE , cache=TRUE }
pitch_swk <- filter(pitch_stats, key1 == "2023-05-15" ,data_title =="個人投手成績（規定投球回以上）" )
#pitch_dataから規定投球回以上投手データ抽出
pitch_dwk <- semi_join(pitch_data,pitch_swk,by = "投手名")
```

## top

### 個人投手成績（規定投球回以上）
```{r  message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
pitch_swk1 <- pitch_swk[4]
pitch_swk2 <- pitch_swk[30:37]
pitch_swk3 <- cbind(pitch_swk1,pitch_swk2)
pitch_swk3 %>% arrange(.,FIP) %>% 
  kable(.,format = "markdown", caption = "", digits = 3) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
```

[top↑](#top)

### 球種構成 個人投手成績（規定投球回以上）
```{r  message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
pitch_dwk <- filter(pitch_dwk, 球種 != "-" )
pitch_dwk1 <- table(pitch_dwk$投手名,pitch_dwk$球種) %>% as.data.frame.array() 
球数合計 <- rowSums(pitch_dwk1)
cbind(pitch_dwk1,球数合計) %>% .[1:7] %>% 
  kable(.,format = "markdown", caption = "" ) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
```


```{r  message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
#table(pitch_dwk$投手名,pitch_dwk$球種) %>% as.data.frame.array() 
cbind(pitch_dwk1,球数合計) %>% .[8:14] %>% 
  kable(.,format = "markdown", caption = "" ) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
```
[top↑](#top)

### 球速帯 個人投手成績（規定投球回以上）
(119:119km/h以下)
```{r message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
table(pitch_dwk$投手名,pitch_dwk$球速帯) %>% 
  kable(.,format = "markdown", caption = "" ) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
```

[top↑](#top)

### swing(%)~球速 個人投手成績（規定投球回以上）
```{r message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
row_sum <- nrow(pitch_dwk)
swing <- table(pitch_dwk$結果5,pitch_dwk$投手名)
contact <- table(pitch_dwk$結果7,pitch_dwk$投手名)
swstr <- table(pitch_dwk$結果6,pitch_dwk$投手名)
k_sum <- table(pitch_dwk$投手名)
# per 算出
swing_per <- swing[1,] / k_sum
contact_per <- contact[1,] /  swing[1,]
swstr_per <- swstr[1,] / k_sum
whiff_per <- swstr[1,] / swing[1,]
# swing data kable  作成
sw_datawk <- rbind(swing_per,contact_per,swstr_per,whiff_per)
sw_data <- round((sw_datawk) *100,2)
sw_data <- t(sw_data)
colnames(sw_data) <- c("swing(%)","contact(%)","swstr(%)","whiff(%)") 
# 球速 data kable　作成
p_max <- aggregate(x=pitch_dwk[c("球速")], by=list(pitch_dwk$投手名), 
                   FUN=max,na.rm = TRUE)
p_mean <- aggregate(x=pitch_dwk[c("球速")], by=list(pitch_dwk$投手名), 
                    FUN=mean,1,na.rm = TRUE)
p_medi <- aggregate(x=pitch_dwk[c("球速")], by=list(pitch_dwk$投手名), 
                    FUN=median,na.rm = TRUE)
p_min <- aggregate(x=pitch_dwk[c("球速")], by=list(pitch_dwk$投手名), 
                   FUN=min,na.rm = TRUE)
p_ver <- cbind(p_max[2],p_mean[2],p_min[2])
p_ver_tabh <- paste("対右打者")
colnames(p_ver) <- c("球速(max)","球速(ave)","球速(min)") 
cbind(sw_data,p_ver) %>% 
  arrange(.,-swstr_per) %>% 
  kable(.,format = "markdown", caption = "" ) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
#
```

[top↑](#top)

### 結果球 個人投手成績（規定投球回以上）
```{r message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center'}
pitch_dwk2 <- filter(pitch_dwk, 結果球 == "*" )
pitch_rslt <- table(pitch_dwk2$結果2,pitch_dwk2$投手名) %>% 
  t() %>% as.data.frame.array()
結果球合計 <- rowSums(pitch_rslt)
#prslt11 <- prslt11 / rowSums(prslt11)
#round((prslt11) *100,2) %>% 
#  format(., nsmall = 2) %>% 
  cbind(pitch_rslt,結果球合計) %>% 
  rename(.data = .,　"空三振" = "空振り") %>% 
  rename(.data = .,　"見三振" = "見逃し") %>% 
  rename(.data = .,　"四死球" = "ボール") %>% 
  dplyr::select(.,単打,長打,本塁打,空三振,見三振,内野ゴ,内野直,内野飛,外野飛,四死球,
                everything()) %>% 
  arrange(.,-球数合計) %>% 
  kable(.,format = "markdown", caption = "" ) %>% 
  kable_styling(bootstrap_options = "striped",full_width = TRUE)
```
###### 球種、球速不明データは除く

[top↑](#top)


### 投球データ-球種 個人投手成績（規定投球回以上）
```{r , message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center',fig.width=6,fig.height=6}
# 投手名10a 全投球内容 散布図
ggplot01p <- 
  ggplot(pitch_dwk,aes(x = X, y = Y, colour = 球種 )) + 
  geom_point(size = 1, alpha = 1) + scale_colour_viridis_d() +
  ylim(180,0) + xlim(0,150) + 
  theme(axis.ticks = element_blank(),axis.text.y = element_blank(),
        axis.text.x = element_blank(),axis.title.x = element_text(size = 10)) +
  xlab("") + ylab("") +
  geom_vline(xintercept = 75) +
  geom_hline(yintercept = 90) +
  geom_rect(aes(xmin = 30, xmax = 120, ymin = 25, ymax = 150),
            fill = "palegreen", colour = "black", alpha = 0.001) 
ggplot01p + facet_wrap(~投手名,ncol=4) 
```
[top↑](#top)

### 投球データ-球速 個人投手成績（規定投球回以上）
```{r , message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center',fig.width=6,fig.height=6}
# 投手名10a 全投球内容 散布図
ggplot02p <- 
  ggplot(pitch_dwk,aes(x = X, y = Y, colour = 球速 )) + 
  geom_point(size = 1, alpha = 1) + scale_colour_viridis_b() +
  ylim(180,0) + xlim(0,150) + 
  theme(axis.ticks = element_blank(),axis.text.y = element_blank(),
        axis.text.x = element_blank(),axis.title.x = element_text(size = 10)) +
  xlab("") + ylab("") +
  geom_vline(xintercept = 75) +
  geom_hline(yintercept = 90) +
  geom_rect(aes(xmin = 30, xmax = 120, ymin = 25, ymax = 150),
            fill = "palegreen", colour = "black", alpha = 0.001) 
ggplot02p + facet_wrap(~投手名,ncol=4) + labs(colour = "km/h")
```

[top↑](#top)

### 投球データ-被安打 個人投手成績（規定投球回以上）
```{r , message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center',fig.width=6,fig.height=5}
pitch_dwk3 <- filter(pitch_dwk, 結果2 == "単打" | 結果2 == "長打"| 結果2 == "本塁打"　)
ggplot03p <- 
  ggplot(pitch_dwk3,aes(x = X, y = Y, colour = 結果2 )) + 
  geom_point(size = 1, alpha = 1) + scale_colour_viridis_d() + 
  ylim(180,0) + xlim(0,150) + 
  theme(axis.ticks = element_blank(),axis.text.y = element_blank(),
        axis.text.x = element_blank(),axis.title.x = element_text(size = 10)) +
  xlab("") + ylab("") +
  geom_vline(xintercept = 75) +
  geom_hline(yintercept = 90) +
  geom_rect(aes(xmin = 30, xmax = 120, ymin = 25, ymax = 150),
            fill = "palegreen", colour = "black", alpha = 0.001) 
ggplot03p + facet_wrap(~投手名,ncol=4) + labs(colour = "被安打")
```

[top↑](#top)

### 投球データ-swstr 個人投手成績（規定投球回以上）
```{r , message=FALSE,warning=FALSE,echo=FALSE,fig.align = 'center',fig.width=6,fig.height=5}
pitch_dwk4 <- filter(pitch_dwk, 結果6 == "swstr"  )
ggplot04p <- 
  ggplot(pitch_dwk4 ,aes(x = X, y = Y, colour = 球種 )) + 
  geom_point(size = 1, alpha = 1) + scale_colour_viridis_d() +
  ylim(180,0) + xlim(0,150) + 
  theme(axis.ticks = element_blank(),axis.text.y = element_blank(),
        axis.text.x = element_blank(),axis.title.x = element_text(size = 10)) +
  xlab("") + ylab("") +
  geom_vline(xintercept = 75) +
  geom_hline(yintercept = 90) +
  geom_rect(aes(xmin = 30, xmax = 120, ymin = 25, ymax = 150),
            fill = "palegreen", colour = "black", alpha = 0.001) 
ggplot04p + facet_wrap(~投手名,ncol=4) 
```

[top↑](#top)

